### ISSUE TITLE
no data found tensorboard

### ISSUE THREAD

**Issue by JaspervDalen** [kukuruza/TF-Visualize-CNN#1]
when I run: 
python utils/generate_logs.py --model $FACENET_DIR/20170512-110547 --logdir $FACENET_DIR/20170512-110547/logs

I get WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'. I already tried to run it using tf 1.3, 1.4, 1.6 and 1.8 but this warning keeps popping up and tensorboard remains empty. Do you have a suggestion?
btw I am trying to replicate your example facenet and these are the errors tensorboard gives:

W0705 11:34:43.685881 Thread-1 application.py:274] path /[[_dataImageSrc]] not found, sending 404
W0705 11:34:43.688213 Thread-2 application.py:274] path /[[_imageURL]] not found, sending 404

**Comment by kukuruza** [comment]
@JaspervDalen 

> I get WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'. I already tried to run it using tf 1.3, 1.4, 1.6 and 1.8 but this warning keeps popping up and tensorboard remains empty. Do you have a suggestion?

Hi, on my TF v1.7 I get the same warning and it is not a problem at all, just a warning, just ignore it. However, just in case, I also uploaded the logs that I generated with `utils/generate_logs.py` (Here is the [link](https://drive.google.com/open?id=1BuSdYwgbMd8MKfxcE1hH8o7-WtHh9Nrd)). Feel free to use.

Next, you start tensorboard with `tensorboard --logdir $FACENET_DIR/20170512-110547/logs`. 
- Make sure that you have that directory (what does `ls $FACENET_DIR/20170512-110547/logs` return?) 
- What do you see in the browser? My tensorboard displays the graph structure correctly:

![graph at tensorboard](https://user-images.githubusercontent.com/3857655/42422944-82175a9a-82a5-11e8-8312-9f44b0e5d4c2.png)

>btw I am trying to replicate your example facenet and these are the errors tensorboard gives:
W0705 11:34:43.685881 Thread-1 application.py:274] path /[[_dataImageSrc]] not found, sending 404
W0705 11:34:43.688213 Thread-2 application.py:274] path /[[_imageURL]] not found, sending 404

That means there is some problem with paths. 
- Did you download `lfw` dataset?
- Try printing out the image paths that are being loaded

**Comment by JaspervDalen** [comment]
ok thank you, it was indeed some wrong path...
